# This workflow will build a Java project with Maven and an Angular Project with node

name: PROJECT CI with Maven and Nodejs

on:
  push:
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build front
      run: npm run build:prod
      working-directory: ./frontend
    - name: Build back;
      run: mvn -B package --file pom.xml
      working-directory: ./backend

       
